spring:
  application:
    name: bugui

greeting-service:
  greeting: "Longavida"
  default-value: "World"

  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: myuser
    password: sa

  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
