spring:
  application:
    name: bugui

  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: myuser
    password: sa

  flyway:
    enabled: true
    locations: classpath:db/migration


bugui:
  greeting: "ola"
  default-value: "Mundo"

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'